modLoader="javafml"
loaderVersion="${forgelike_loader_ver}"
license="${license}"
issueTrackerURL="${issue_tracker}"
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
logoFile="${icon}"
authors="${authors}"
description='''
${description}
'''
credits = ${credits}

${mixin_field}

${dependencies_field}
